version: "2"
services:
  slack:
    build: slack
    ports:
      - "4000:80"
    env_file: slack/.env.development
    volumes:
      - ./slack:/myapp
      - slackbundle:/usr/local/bundle
volumes:
  slackbundle:
