source "https://rubygems.org"

gem "rspotify"
gem "slack-ruby-bot", "~> 0.10.1"
gem "celluloid-io" # slack bot requires this or faye-websocket
gem "sonos"

group "test" do
  gem "rspec"
  gem "rack-test"
  gem "vcr"
  gem "webmock"
end
