source "https://rubygems.org"

gem "rspotify"
gem "slack-ruby-bot", "~> 0.9.0" # 0.10.0 is buggy
gem "celluloid-io" # slack bot requires this or faye-websocket

group "test" do
  gem "rspec"
  gem "rack-test"
  gem "vcr"
  gem "webmock"
end
